version: 0.2

env:
  variables:
    ACCOUNT_ID: 557690580165
    REGION: us-west-1
    REPO_NAME: expense
    IMAGE_TAG: latest
    IMAGE_URI: 557690580165.dkr.ecr.us-west-1.amazonaws.com/expimg-nc:latest
    SONAR_HOST_URL: http://44.212.5.76
    SONAR_PROJECT_KEY: NCExpense
    SONAR_LOGIN: sqp_983f8c5b8900c6f797da4c8b9396f35bdbb5e89e

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven, Docker, and Trivy...
      - yum install -y maven docker
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

  build:
    commands:
      - echo Building JAR inside app-tier...
      - mvn clean package -DskipTests
      - echo Running SonarQube Analysis with tests skipped...
      - mvn clean verify sonar:sonar -DskipTests -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_LOGIN
      - echo Building Docker image...
      - docker build -t $REPO_NAME:$IMAGE_TAG .
      - docker tag $REPO_NAME:$IMAGE_TAG $IMAGE_URI
      - echo Scanning image using Trivy...
      - trivy image --exit-code 0 --severity HIGH,CRITICAL $IMAGE_URI

  post_build:
    commands:
      - echo Pushing image to Amazon ECR...
      - docker push $IMAGE_URI
      - echo Preparing Kubernetes manifests...
      - mkdir -p k8s-out
      - sed "s|IMAGE_PLACEHOLDER|$IMAGE_URI|g" deployment.yaml > k8s-out/deployment.yaml
      - cp service.yaml k8s-out/service.yaml
      - echo Done preparing artifacts.

artifacts:
  base-directory: k8s-out
  files:
    - deployment.yaml
    - service.yaml
